config/routes.rb
IdeaORama::Application.routes.draw do
  devise_for :users

  resources :topics do
    resources :ideas
  end

  root :to => "topics#index"

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :ideas
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!

  def new
    @topic = Topic.find(params[:topic_id])
    @idea = Idea.new
  end

  def create
    idea = Idea.new
    idea.title = params[:idea][:title]

    if idea.save
      flash[:notice] = 'Neue Idee gespeichert.'
      topic = Topic.find(params[:topic_id])
      redirect_to topic_path(topic)
    else
      flash[:error] = 'Fehler beim Speichern!'
      render :action => 'new'
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @topics }
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  # prepare for new entry
  def new
    @topic = Topic.new
  end
  
  # new entry has been submitted
  def create
    topic = Topic.new
    topic.title = params[:topic][:title]
    if topic.save
      flash[:notice] = 'Neuer Topic angelegt.'
      redirect_to :action => 'index'
    else
      flash[:error] = 'Doh. Fehler beim Speichern eines neuen Topics!'
      render :action => 'new'
    end
  end

  def update
    Log.info("blurb")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/idea_helper.rb
module IdeaHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/ideas/new.html.erb
<div class="container">
  <div class="row">
    <div class="ninecol">
      <h1>idea-o-rama</h1>
    </div>
    <div class="threecol last">
      <em><%=h @topic.title %></em>
    </div>
  </div>
</div> <%# "container" %>

<div class="form">
  <div class="form_content">
    <% form_for ([@topic, @idea]) do |form| %>
    <fieldset>
      <legend>Neue Idee</legend>
      <div>
	<%= form.label :title, "Idee: " %>
	<%= form.text_field :title %>
      </div>
      <%= submit_tag "Idee anlegen", :class => "submit" %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- <meta charset="utf-8" /> -->
  <title>idea-o-rama</title>
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0" /> -->

  <%= stylesheet_link_tag "1140" %>
  <!--[if lte IE 9]>
  <%= stylesheet_link_tag "ie.css" %>
  <![endif]-->
  <%= stylesheet_link_tag "layout" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="user_nav">
  <% if user_signed_in? %>
  Hi, <%= current_user.email %>
  |
  <%= link_to "Logout", destroy_user_session_path %>
  <% else %>
  <%= link_to "Registrieren", new_user_registration_path %>
  | 
  <%= link_to "Anmelden", new_user_session_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/topics/index.html.erb
<div class="container">
  <div class="row">
    <div class="ninecol">
      <h1>idea-o-rama</h1>
    </div>
    <div class="threecol last">
      <%= link_to 'Neues Thema', new_topic_path %>
    </div>
  </div>
</div> <!-- class="container" -->

<div class="container">
  <% @topics.each do |topic| %>
  <div class="row">
    <div class="onecol">3</div>
    <div class="eightcol"><%=h link_to topic.title, topic %></div>
    <div class="threecol last">&nbsp;</div>
  </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="row">
    <div class="ninecol">
      <h1>Wishful Thinking</h1>
    </div>
    <div class="threecol last">
      &nbsp;
    </div>
  </div>
</div> <%# "container" %>

<div class="form">
  <div class="form_content">
    <% form_for @topic do |form| %>
    <fieldset>
      <legend>Neues Thema</legend>
      <div>
	<%= form.label :title, "Thema: " %>
	<%= form.text_field :title %>
      </div>
      <%= submit_tag "Thema anlegen", :class => "submit" %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="container">
  <div class="row">
    <div class="ninecol">
      <h1>idea-o-rama: <em><%= @topic.title %></em></h1>
    </div>
    <div class="threecol last">
      <%= link_to 'Neue Idee', new_topic_idea_path(@topic) %>
    </div>
  </div>
</div> <!-- class="container" -->

<div class="container">
  <%# @topic.ideas.each do |ideas| %>
  <div class="row">
    <div class="onecol">3</div>
    <div class="eightcol"><%# =h idea.title %>
    </div>
    <div class="threecol last">&nbsp;</div>
  </div>
  <%# end %>
</div>